<?php

function commerce_product_ui_new() {
	return [
		'type' => ""
		'name' =>"",
		'description' => "",
		"help" =>"",
		'revision' => 1
	];
}

function commerce_product_ui_product_type_save($product_save, $configure = TRUE, $skip_reset = FALSE) {
	$op = drupal_write_record('commerce_product_type', $product_type, empty($product_type['type']) ? 'type' : []);

	if ( !empty($product_type['is_new']) && $op !== FALSE) {
		field_attach_create_bundle('commerce_product', $product_type['type']);

		if ($configure) {
			commerce_product_configure_product_type($product_type['type']);
		}

		module_invoke_all('commerce_product_type_insert', $product_type, $skip_reset);
	} elseif ($op !== FALSE) {
			module_invoke_all('commerce_product_type_update', $product_type, $skip_reset);
	}		

	if (!$skip_reset) {
		commerce_product_types_reset();
		variable_set('menu_rebuild_needed', TRUE);
	}

	return $op;
}

function commerce_product_ui_product_add_any_access() {
	if (user_access('administer commerce_product entities')) {
		return TRUE;
	}

	foreach (commerce_product_types() as $type => $product_type) {
		if (commerce_product_access('create', commerce_product_new($type))) {
			return TRUE;
		}
	}
}

function commmerce_product_ui_menu() {
	
	$items['admin/commerce/products/add'] = array(
    'title' => 'Add a product',
    'description' => 'Add a new product for sale.',
    'page callback' => 'commerce_product_ui_add_page',
    'access callback' => 'commerce_product_ui_product_add_any_access',
    'weight' => 10,
    'file' => 'includes/commerce_product_ui.products.inc',
   );
}

