<?php

function commerce_price_create_instance($field_name, 	$entity_type, $bundle, $label, $weight =0, $calculation = FALSE, $display = []) {
	commerce_activate_field();
	field_cache_clear();
	$field = field_info_field($field_name);
	$instance = field_info_instance($entity_type, $field_name, $bundle);

	if (empty($field)) {
		$field =[
			'field_name' => 	$field_name,
			'type' => 'commerce_price',
			'cardinality' =>1,
			'entity_types' =>[$entity_type],
			'translatable' => FALSE,
			'locked' => TRUE,
		];

		field_create_field($field);
	}

	if (empty($instance)) {
		$instance = [
			'field_name' => $field_name,
			'entity_type' => $entity_type,
			'label' => $label,
			'required' => TRUE,
			'settings' => [],
			'widget' => [
				'type' => 'commerce_price_full',
				'weight' => $weight,
				'settings' => [
					'currency_code' => 'default'
				],
			],
			'display' => []
		];

		$entity_info = entity_get_info($entity_type);
		$entity_info['view_modes'] += [
			'default' => [],
			'node_teaser' => []
		];

		foreach ($entity_info['view modes'] as $view_mode => $data) {
			$instance['display'][$view_mode] = $display + [
				'label' => 'hidden',
				'type' => 'commerce_price_formatted_amount',
				'settings' => [
					'calculation' => $calculation
				],
				'weight' => $weight
			];
		}
		field_create_instance($instance);
	}
}
